/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as TagTagRouteImport } from './routes/tag/$tag'
import { Route as BlogIdRouteImport } from './routes/blog/$id'
import { Route as StoryStoryIdIndexRouteImport } from './routes/story/$storyId/index'
import { Route as StoryStoryIdCharactersRouteImport } from './routes/story/$storyId/characters'
import { Route as BlogCategoryCategoryRouteImport } from './routes/blog/category/$category'
import { Route as StoryStoryIdChapterNumberRouteImport } from './routes/story/$storyId/chapter/$number'

const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const TagTagRoute = TagTagRouteImport.update({
  id: '/tag/$tag',
  path: '/tag/$tag',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIdRoute = BlogIdRouteImport.update({
  id: '/blog/$id',
  path: '/blog/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryStoryIdIndexRoute = StoryStoryIdIndexRouteImport.update({
  id: '/story/$storyId/',
  path: '/story/$storyId/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryStoryIdCharactersRoute = StoryStoryIdCharactersRouteImport.update({
  id: '/story/$storyId/characters',
  path: '/story/$storyId/characters',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogCategoryCategoryRoute = BlogCategoryCategoryRouteImport.update({
  id: '/blog/category/$category',
  path: '/blog/category/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryStoryIdChapterNumberRoute =
  StoryStoryIdChapterNumberRouteImport.update({
    id: '/story/$storyId/chapter/$number',
    path: '/story/$storyId/chapter/$number',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/stories': typeof StoriesRoute
  '/blog/$id': typeof BlogIdRoute
  '/tag/$tag': typeof TagTagRoute
  '/blog/': typeof BlogIndexRoute
  '/blog/category/$category': typeof BlogCategoryCategoryRoute
  '/story/$storyId/characters': typeof StoryStoryIdCharactersRoute
  '/story/$storyId/': typeof StoryStoryIdIndexRoute
  '/story/$storyId/chapter/$number': typeof StoryStoryIdChapterNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/stories': typeof StoriesRoute
  '/blog/$id': typeof BlogIdRoute
  '/tag/$tag': typeof TagTagRoute
  '/blog': typeof BlogIndexRoute
  '/blog/category/$category': typeof BlogCategoryCategoryRoute
  '/story/$storyId/characters': typeof StoryStoryIdCharactersRoute
  '/story/$storyId': typeof StoryStoryIdIndexRoute
  '/story/$storyId/chapter/$number': typeof StoryStoryIdChapterNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/stories': typeof StoriesRoute
  '/blog/$id': typeof BlogIdRoute
  '/tag/$tag': typeof TagTagRoute
  '/blog/': typeof BlogIndexRoute
  '/blog/category/$category': typeof BlogCategoryCategoryRoute
  '/story/$storyId/characters': typeof StoryStoryIdCharactersRoute
  '/story/$storyId/': typeof StoryStoryIdIndexRoute
  '/story/$storyId/chapter/$number': typeof StoryStoryIdChapterNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/stories'
    | '/blog/$id'
    | '/tag/$tag'
    | '/blog/'
    | '/blog/category/$category'
    | '/story/$storyId/characters'
    | '/story/$storyId/'
    | '/story/$storyId/chapter/$number'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/stories'
    | '/blog/$id'
    | '/tag/$tag'
    | '/blog'
    | '/blog/category/$category'
    | '/story/$storyId/characters'
    | '/story/$storyId'
    | '/story/$storyId/chapter/$number'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/stories'
    | '/blog/$id'
    | '/tag/$tag'
    | '/blog/'
    | '/blog/category/$category'
    | '/story/$storyId/characters'
    | '/story/$storyId/'
    | '/story/$storyId/chapter/$number'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  StoriesRoute: typeof StoriesRoute
  BlogIdRoute: typeof BlogIdRoute
  TagTagRoute: typeof TagTagRoute
  BlogIndexRoute: typeof BlogIndexRoute
  BlogCategoryCategoryRoute: typeof BlogCategoryCategoryRoute
  StoryStoryIdCharactersRoute: typeof StoryStoryIdCharactersRoute
  StoryStoryIdIndexRoute: typeof StoryStoryIdIndexRoute
  StoryStoryIdChapterNumberRoute: typeof StoryStoryIdChapterNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tag/$tag': {
      id: '/tag/$tag'
      path: '/tag/$tag'
      fullPath: '/tag/$tag'
      preLoaderRoute: typeof TagTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$id': {
      id: '/blog/$id'
      path: '/blog/$id'
      fullPath: '/blog/$id'
      preLoaderRoute: typeof BlogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story/$storyId/': {
      id: '/story/$storyId/'
      path: '/story/$storyId'
      fullPath: '/story/$storyId/'
      preLoaderRoute: typeof StoryStoryIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story/$storyId/characters': {
      id: '/story/$storyId/characters'
      path: '/story/$storyId/characters'
      fullPath: '/story/$storyId/characters'
      preLoaderRoute: typeof StoryStoryIdCharactersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/category/$category': {
      id: '/blog/category/$category'
      path: '/blog/category/$category'
      fullPath: '/blog/category/$category'
      preLoaderRoute: typeof BlogCategoryCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story/$storyId/chapter/$number': {
      id: '/story/$storyId/chapter/$number'
      path: '/story/$storyId/chapter/$number'
      fullPath: '/story/$storyId/chapter/$number'
      preLoaderRoute: typeof StoryStoryIdChapterNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  StoriesRoute: StoriesRoute,
  BlogIdRoute: BlogIdRoute,
  TagTagRoute: TagTagRoute,
  BlogIndexRoute: BlogIndexRoute,
  BlogCategoryCategoryRoute: BlogCategoryCategoryRoute,
  StoryStoryIdCharactersRoute: StoryStoryIdCharactersRoute,
  StoryStoryIdIndexRoute: StoryStoryIdIndexRoute,
  StoryStoryIdChapterNumberRoute: StoryStoryIdChapterNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
